enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config


[YouTube-Extended]
enabled = "true"
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "module"
included-patches = "'Custom branding heading' 'MaterialYou' 'Settings icons'"
excluded-patches = "'Custom branding name YouTube' 'Enable debug logging'"
version = "19.16.38"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
