enable-magisk-update = true
parallel-jobs = 1
compression-level = 9

[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'MaterialYou' 'Return YouTube Username'"
patcher-args = "--legacy-options=options.json"
build-mode = "both"


[X]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter"
apkmirror-dpi = "120-640dpi"

